Mypage
MySpooot/MySpot-Web pull request #60
Opened 2022-04-02 11:21 UTC by haeunbae

됐나

2022-04-02 16:07 UTC, InJaEE requested changes

2022-04-02 16:07 UTC, InJaEE commented on src/pages/MyPage/MyPage.tsx
> +            {nicknamePopup && <Modal id={me?.id} setOpen={() => setNicknamePopup(false)}></Modal>}
전체적으로 변수 이름 작성하실때 최대한 명시적인 이름을 사용하시면 좋을듯합니다.

여기서 Modal이라고 작성하시면 처음 코드를 보는 사람은 component 폴더의 Modal인지 새로 정의한 NicknameModal인지 헷갈릴 수 있습니다.

프롭스인 setOpen의 경우에도 하는 역할은 닉네임모달을 닫는 역할인데 이름이 역할과 달라서 헷갈릴거 같네요

그리고 jsx태그 안에 들어갈 코드가 없다면 바로 닫아주는게 좋습니다.
<Modal />

2022-04-02 16:07 UTC, InJaEE commented on src/atoms/me.ts
> +};
위에 updateState와 더불어서 사용하는 곳이 없으면 삭제하는게 좋을것 같습니다.

2022-04-02 16:07 UTC, InJaEE commented on src/api/auth/auth.ts
> +export const createUserImg = (file: FormData) => {
여기도 file: FormData 이 부분 다른 API처럼 사용형식 맞춰주세요 :)

2022-04-02 16:10 UTC, InJaEE commented on src/api/auth/auth.ts
> +    return request<UpdateUserNicknameResponse>({ method: 'put', url: `/user`, data: { nickname } });
```js
<UpdateUserNicknameResponse>
```
이 부분은 기존의 updateUserNickname과 response가 같다고 하더라도 다른 API이기 때문에 새로 작성해서 타입 지정해주는게 둘중 하나의 API의 response가 변경될 가능성이 있어서 좋습니다.

2022-04-02 16:13 UTC, InJaEE commented on src/api/auth/auth.ts
> +export const updateUserNicknameMypage = (userId: number | undefined, nickname: string) => {
혹시 궁금하실까봐 적어두자면
기존에 param, body를 속성이 한개이더라도 객체형식으로 타입을 지정해두는 이유는
추후 백엔드에서 param, body등의 타입을 패키지로 올려서 프론트엔드에서 다운로드해서 사용하는 상황이 오게되었을때 형식을 맞추기 위함입니다.

2022-04-02 16:22 UTC, InJaEE commented on src/components/NicknameModal/NicknameModal.tsx
> +    id: number | undefined;
api/auth 쪽에서 말씀드린대로 필요없는 부분 삭제하게되면 여기 id도 삭제해도 되겠네요

2022-04-04 00:43 UTC, haeunbae commented on src/pages/MyPage/MyPage.tsx
> +            getMeHelper.setQueryData({ ...me, thumbnail: resultThumnail });
저 이렇게 수정하면 { ...me, thumbnail: resultThumnail }이 부분에
`'(me: GetMeResponse | undefined) => { thumbnail: string; id?: number | undefined; nickname?: string | undefined; }' 형식의 인수는 'Updater<GetMeResponse | undefined, GetMeResponse | undefined>' 형식의 매개 변수에 할당될 수 없습니다.
  '(me: GetMeResponse | undefined) => { thumbnail: string; id?: number | undefined; nickname?: string | undefined; }' 형식은 'DataUpdateFunction<GetMeResponse | undefined, GetMeResponse | undefined>' 형식에 할당할 수 없습니다.
    '{ thumbnail: string; id?: number | undefined; nickname?: string | undefined; }' 형식은 'GetMeResponse' 형식에 할당할 수 없습니다.
      'id' 속성은 '{ thumbnail: string; id?: number | undefined; nickname?: string | undefined; }' 형식에서 선택적이지만 'GetMeResponse' 형식에서는 필수입니다.`
      
이런식으로 TS 에러 뜨는것 같은데 이해가 잘 안됍니다...ㅜㅜ

2022-04-04 00:51 UTC, InJaEE commented on src/pages/MyPage/MyPage.tsx
> +            getMeHelper.setQueryData({ ...me, thumbnail: resultThumnail });
에러코드 읽어보시면 me가 undefined일 경우가 있다고 말하는거 같은데

```js
getMeHelper.setQueryData(me =>
    if(!me) return;
    return { ...me, thumbnail: resultThumnail }
);
```

이렇게 해보시겠어요?

2022-04-04 01:02 UTC, haeunbae commented on src/pages/MyPage/MyPage.tsx
> +            getMeHelper.setQueryData({ ...me, thumbnail: resultThumnail });
해봤는데 에러는 똑같아요. 뭔가 me가 문제가 아니라 id가 옵셔널이라는 것 같은데...이해가...ㅜ

2022-04-04 01:05 UTC, InJaEE commented on src/pages/MyPage/MyPage.tsx
> +            getMeHelper.setQueryData({ ...me, thumbnail: resultThumnail });
혹시 GetMeResponse 수정해서 그런거 아닌가요?

2022-04-04 01:10 UTC, haeunbae commented on src/pages/MyPage/MyPage.tsx
> +            getMeHelper.setQueryData({ ...me, thumbnail: resultThumnail });
앗 id랑 nickname ?를 지웠었네여ㅜㅜ

2022-04-04 01:10 UTC, InJaEE commented on src/pages/MyPage/MyPage.tsx
> +            getMeHelper.setQueryData({ ...me, thumbnail: resultThumnail });
? 지우는건 맞아요

2022-04-04 01:11 UTC, InJaEE commented on src/pages/MyPage/MyPage.tsx
> +            getMeHelper.setQueryData({ ...me, thumbnail: resultThumnail });
?지우면 에러나나요?

2022-04-04 01:12 UTC, haeunbae commented on src/pages/MyPage/MyPage.tsx
> +            getMeHelper.setQueryData({ ...me, thumbnail: resultThumnail });
지금 `export type GetMeResponse = {
    id?: number;
    nickname?: string;
    thumbnail?: string;
};` 이렇게 해야 에러가 안나요

2022-04-04 01:13 UTC, haeunbae commented on src/pages/MyPage/MyPage.tsx
> +            getMeHelper.setQueryData({ ...me, thumbnail: resultThumnail });
지워서 에러난것 같아요

2022-04-04 01:13 UTC, InJaEE commented on src/pages/MyPage/MyPage.tsx
> +            getMeHelper.setQueryData({ ...me, thumbnail: resultThumnail });
GetMeResponse의 id, nickname은 무조건 있는 값이기 때문에 ? 없는게 맞습니다

2022-04-04 01:13 UTC, InJaEE commented on src/pages/MyPage/MyPage.tsx
> +            getMeHelper.setQueryData({ ...me, thumbnail: resultThumnail });
다른거 잘못된거 있는지 확인해볼게요

2022-04-04 01:17 UTC, haeunbae commented on src/api/auth/auth.ts
> +export const createUserImg = (file: FormData) => {
혹시 return request<string> 여기에도 string대신 request전용 타입? 처럼 만들어서 써줘야하나요?

2022-04-04 01:18 UTC, InJaEE commented on src/api/auth/auth.ts
> +export const createUserImg = (file: FormData) => {
swagger 보시면 여기는 return되는게 string이여서 그대로 두셔도 될듯 합니다

2022-04-04 12:26 UTC, InJaEE requested changes

2022-04-04 12:26 UTC, InJaEE commented on src/pages/MyPage/MyPage.tsx
> +            getMeHelper.setQueryData(me => ({ ...me, thumbnail: resultThumnail }));
추가설명)
getMeresponse의 옵셔널은 변경하고나면 일단 79줄이 빨간색으로 에러표시가나게될겁니다
React의 useState가 return하는 setState류의 함수들은 사용하는 방법이 두가지가 있습니다.

1. 바로 값을 넣어준다.
```js
const [data, setData] = useState('Hi');

setData('Hello'); // data가 'Hi'에서 'Hello'로 바뀐다
```

2. 함수형태로 사용하여 이전 값을 동기적으로 활용한다.
```js
const [data, SetData] = useState('Hi');

setData(data => {
   return data + '!'; 
}); // data가 'Hi'에서 'Hi!'로 바뀐다
```

여기서 getMeHelper.setQueryData도 useState의 setData와 똑같이 보시면 됩니다.
getMeHelper.setQueryData가 가지고 있는 처음의 값인 me는 유저가 로그인하지 않았을 경우에 undefined입니다.
2번째 사용방법대로 사용하게되면 me가 undefined일 경우에 스프레드연산자를 사용하지 못하니까 그 전에 undefined인 경우를 없애주어야 합니다.

```js
getMeHelper.setQueryData(me => {
    if(!me) return; // me가 undefined인 경우를 없애준다.
    
    return {...me, thumbnail: resultThumbnail};
});
```

2022-04-04 12:26 UTC, InJaEE commented on src/pages/MyPage/MyPage.tsx
> +                    </InputImg>
전체 width줄여가면서 테스트해보시면  InputImg가 relative가 아니라서 카메라 아이콘이 absolute라도 원하는 위치에 가지 않습니다 ㅠㅠ

2022-04-04 12:26 UTC, InJaEE commented on src/pages/MyPage/MyPage.tsx
> +                    </InputImg>
지금 여기말고 다른곳도 반응형으로 테스트해보면 스타일이 깨지는곳이 많은데
스타일링은 일단 머지하고 나중에 같이 진행하시죠

2022-04-04 12:26 UTC, InJaEE commented on src/pages/MyPage/MyPage.tsx
> +            const resultThumnail = await createUserImg({ file: formData });
이미지 변경하는거 저 안되는거 같은데 작동하시나요?

2022-04-07 06:44 UTC, closed without merging